import type { Metadata } from 'next';

import { EnvProvider } from './env-provider';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="/css/style.css" />
      </head>
      <body>
        <div id="page">
          <header id="masthead" className="site-header">
            <div className="logo">Memoアプリ</div>
          </header>
          <main id="main" className="main">
            <EnvProvider env={{ API_BASE_URL: getApiBaseUrl() }}>{children}</EnvProvider>
          </main>
        </div>
      </body>
    </html>
  );
}

export const getApiBaseUrl = () => {
  if (process.env.CODESPACE_NAME) return `https://${process.env.CODESPACE_NAME}-8000.app.github.dev`;
  if (process.env.API_BASE_URL) return process.env.API_BASE_URL;

  return 'http://localhost:8000';
};
